x = "Hello Python" # string
x = 20 # integer
x = 20.5 # float
x = 1j # complex
x = ['apple', 'orange', 'banana'] # list
x = ('apple', 'orange', 'banana') # tuple
x = range(6) # range
x = {'name': 'Bekzod', 'age': 20} # dict
x = {'apple', 'orange', 'banana'} # set
x = frozenset({'apple', 'orange', 'banana'}) # frozenset
x = True # bool
x = b"Hello" # bytes
x = bytearray(5) # bytearray
x = memoryview(bytes(5)) # memoryview
